// lib/curriculum.ts
import type { SkillNode, Badge, DailyChallenge } from './types'

export const SKILL_TREE: SkillNode[] = [
  // ── CODING TRACK ──────────────────────────────────
  {
    id: 'coding-basics',
    title: 'Coding Basics',
    emoji: '💻',
    description: 'Learn what code is and how computers understand instructions.',
    xpReward: 30,
    order: 1,
    requiredNodes: [],
    track: 'coding',
    ageGroups: ['mini', 'junior', 'pro', 'expert'],
    lessons: ['what-is-code', 'your-first-program', 'variables'],
  },
  {
    id: 'logic-loops',
    title: 'Logic & Loops',
    emoji: '🔄',
    description: 'Make your code repeat and make decisions.',
    xpReward: 40,
    order: 2,
    requiredNodes: ['coding-basics'],
    track: 'coding',
    ageGroups: ['mini', 'junior', 'pro', 'expert'],
    lessons: ['if-else', 'loops', 'functions-intro'],
  },
  {
    id: 'web-basics',
    title: 'Web & HTML',
    emoji: '🌐',
    description: 'Build your first webpage from scratch.',
    xpReward: 50,
    order: 3,
    requiredNodes: ['logic-loops'],
    track: 'coding',
    ageGroups: ['junior', 'pro', 'expert'],
    lessons: ['html-intro', 'css-styling', 'your-first-page'],
  },
  {
    id: 'interactive-apps',
    title: 'Interactive Apps',
    emoji: '⚡',
    description: 'Add JavaScript to make things click, move, and respond.',
    xpReward: 60,
    order: 4,
    requiredNodes: ['web-basics'],
    track: 'coding',
    ageGroups: ['pro', 'expert'],
    lessons: ['js-basics', 'dom-manipulation', 'events'],
  },
  {
    id: 'react-basics',
    title: 'React & Components',
    emoji: '⚛️',
    description: 'Build modern apps with React like the pros.',
    xpReward: 80,
    order: 5,
    requiredNodes: ['interactive-apps'],
    track: 'coding',
    ageGroups: ['expert'],
    lessons: ['react-intro', 'components', 'state-props'],
  },

  // ── AI TRACK ──────────────────────────────────────
  {
    id: 'ai-intro',
    title: 'What is AI?',
    emoji: '🧠',
    description: 'Discover how machines learn and why AI is everywhere.',
    xpReward: 30,
    order: 1,
    requiredNodes: [],
    track: 'ai',
    ageGroups: ['mini', 'junior', 'pro', 'expert'],
    lessons: ['ai-history', 'how-machines-learn', 'ai-in-daily-life'],
  },
  {
    id: 'ml-basics',
    title: 'Machine Learning',
    emoji: '📊',
    description: 'Teach a computer to recognize patterns — just like a brain!',
    xpReward: 50,
    order: 2,
    requiredNodes: ['ai-intro'],
    track: 'ai',
    ageGroups: ['junior', 'pro', 'expert'],
    lessons: ['training-data', 'ml-models', 'classify-images'],
  },
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering',
    emoji: '✍️',
    description: 'Learn to talk to AI models like a pro and get amazing results.',
    xpReward: 40,
    order: 3,
    requiredNodes: ['ai-intro'],
    track: 'ai',
    ageGroups: ['junior', 'pro', 'expert'],
    lessons: ['what-is-a-prompt', 'prompt-patterns', 'build-ai-tool'],
  },
  {
    id: 'build-ai-app',
    title: 'Build an AI App',
    emoji: '🤖',
    description: 'Use an AI API to power your own real application.',
    xpReward: 80,
    order: 4,
    requiredNodes: ['ml-basics', 'prompt-engineering'],
    track: 'ai',
    ageGroups: ['pro', 'expert'],
    lessons: ['api-calls', 'ai-chatbot', 'ai-image-generator'],
  },

  // ── ENTREPRENEURSHIP TRACK ────────────────────────
  {
    id: 'biz-mindset',
    title: 'Entrepreneur Mindset',
    emoji: '💡',
    description: 'Think like a founder: solve problems, spot opportunities.',
    xpReward: 30,
    order: 1,
    requiredNodes: [],
    track: 'entrepreneurship',
    ageGroups: ['mini', 'junior', 'pro', 'expert'],
    lessons: ['problem-solving', 'growth-mindset', 'famous-kid-founders'],
  },
  {
    id: 'idea-validation',
    title: 'Validate Your Idea',
    emoji: '🔍',
    description: 'Learn how to test if your idea is actually good before building.',
    xpReward: 40,
    order: 2,
    requiredNodes: ['biz-mindset'],
    track: 'entrepreneurship',
    ageGroups: ['junior', 'pro', 'expert'],
    lessons: ['customer-discovery', 'mvp', 'feedback-loops'],
  },
  {
    id: 'build-brand',
    title: 'Build Your Brand',
    emoji: '🎨',
    description: 'Design a name, logo, and identity for your project or company.',
    xpReward: 50,
    order: 3,
    requiredNodes: ['idea-validation'],
    track: 'entrepreneurship',
    ageGroups: ['junior', 'pro', 'expert'],
    lessons: ['naming', 'logo-design', 'brand-voice'],
  },
  {
    id: 'pitch-it',
    title: 'Pitch Your Idea',
    emoji: '🎤',
    description: 'Create a compelling pitch deck and present your idea with confidence.',
    xpReward: 60,
    order: 4,
    requiredNodes: ['build-brand'],
    track: 'entrepreneurship',
    ageGroups: ['pro', 'expert'],
    lessons: ['pitch-structure', 'storytelling', 'investor-mindset'],
  },
]

export const ALL_BADGES: Badge[] = [
  { id: 'first-lesson',  name: 'First Step',      emoji: '👟', description: 'Completed your very first lesson!', condition: '1 lesson',    rarity: 'common'    },
  { id: 'streak-3',      name: '3-Day Streak',     emoji: '🔥', description: 'Learned 3 days in a row!',         condition: '3-day streak', rarity: 'common'    },
  { id: 'streak-7',      name: 'Week Warrior',     emoji: '⚡', description: '7 days of learning — unstoppable!', condition: '7-day streak', rarity: 'rare'      },
  { id: 'xp-100',        name: 'Century Club',     emoji: '💯', description: 'Earned 100 XP!',                   condition: '100 XP',       rarity: 'common'    },
  { id: 'xp-500',        name: 'XP Legend',        emoji: '🌟', description: 'Earned 500 XP — you\'re on fire!', condition: '500 XP',       rarity: 'rare'      },
  { id: 'lessons-5',     name: 'Quick Learner',    emoji: '📚', description: 'Finished 5 lessons!',              condition: '5 lessons',    rarity: 'common'    },
  { id: 'lessons-10',    name: 'Knowledge Seeker', emoji: '🎓', description: '10 lessons completed. Wow!',       condition: '10 lessons',   rarity: 'rare'      },
  { id: 'dream-builder', name: 'Dream Builder',    emoji: '🚀', description: 'Started building your dream project!', condition: 'special',   rarity: 'epic'      },
  { id: 'ai-pioneer',    name: 'AI Pioneer',       emoji: '🤖', description: 'Completed the full AI track!',     condition: 'ai track',     rarity: 'legendary' },
]

export const getDailyChallenge = (ageGroup: string): DailyChallenge => {
  const challenges: Record<string, DailyChallenge> = {
    mini: {
      id: 'daily-mini-' + new Date().toDateString(),
      title: 'Spot the AI!',
      description: 'Can you find 3 things in your home that use AI or computers to work? Draw or describe them!',
      emoji: '🔍',
      xpReward: 20,
      type: 'think',
      expiresAt: new Date(Date.now() + 86400000).toISOString(),
    },
    junior: {
      id: 'daily-junior-' + new Date().toDateString(),
      title: 'Algorithm Chef',
      description: 'Write step-by-step instructions to make your favorite snack. Be so precise a robot could follow it!',
      emoji: '👨‍🍳',
      xpReward: 25,
      type: 'think',
      expiresAt: new Date(Date.now() + 86400000).toISOString(),
    },
    pro: {
      id: 'daily-pro-' + new Date().toDateString(),
      title: 'Prompt Battle',
      description: 'Write 3 different prompts to ask an AI to write a story. Which one gives the best result? Why?',
      emoji: '✍️',
      xpReward: 30,
      type: 'build',
      expiresAt: new Date(Date.now() + 86400000).toISOString(),
    },
    expert: {
      id: 'daily-expert-' + new Date().toDateString(),
      title: 'Build a Mini Tool',
      description: 'Create a simple function that takes a sentence and counts the words in it. Test it with 3 examples.',
      emoji: '⚙️',
      xpReward: 40,
      type: 'build',
      expiresAt: new Date(Date.now() + 86400000).toISOString(),
    },
  }
  return challenges[ageGroup] || challenges.pro
}
